BREAK IT: try to use JSR package with default Nx-generated setup (doesn't work[1])
[1]: nx run node-cli-app:build

> nx run node-cli-app:build:production

apps/node-cli-app/src/NodeCliApp.ts:1:49 - error TS2307: Cannot find module '@axhxrx/date' or its corresponding type declarations.
  There are types at '/home/protiev/axhxrx-nx-deno-jsr-integration-test-2024-06/node_modules/@axhxrx/date/_dist/mod.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.

> 1 | import { dateToIS08601WithTimeZoneOffset } from '@axhxrx/date';
    |                                                 ^
  2 | export class NodeCliApp
  3 | {
  4 |   constructor(

Found 1 error.

——————————————————————————————————————————————————————————————————————————————————

 NX   Ran target build for project node-cli-app (481ms)

   ✖  1/1 failed
   ✔  0/1 succeeded [0 read from cache]

┌[protiev@fed-40-container] [/dev/pts/7] [BREAK-THE-FUCKING-OLD-WORLD-with-type-bundle-in-package-json ⚡] [1]
└[~/axhxrx-nx-deno-jsr-integration-test-2024-06]>